import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { connectWallet } from "../components/web3connect";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  async function verifyUser() {
    const output = await connectWallet();
    // console.log(output);
    if (output === 0) {
      router.push("/denied");
    } else {
      router.push("/welcome");
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Gated Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Connect to App{" "}
          <button style={{ fontSize: "30px" }} onClick={verifyUser}>
            Connect Wallet
          </button>
        </h1>

        <p>
          Welcome: When you have our NFT
          <br />
          Access Denied: When you don't have our NFT{" "}
        </p>
      </main>
    </div>
  );
}
